---
- name: Crear directorio de configuración
  file:
    path: /opt/haproxy
    state: directory

- name: Generar configuración HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /opt/haproxy/haproxy.cfg

- name: Ejecutar contenedor HAProxy
  docker_container:
    name: haproxy
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - /opt/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart_policy: always

